<table width="710" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td colspan="5" id="lecture" style="padding-top:20px;"><h1>Nuqat.me Website Terms of Use</h1></td>
    </tr>
  <tr>
    <td colspan="5"></td>
    </tr>
  <tr>
    <td colspan="5"><p>The following describes the terms and  conditions under which the services of this Nuqat.me website (this  &quot;Website&quot;) are provided (this &quot;Agreement&quot;). By accessing  this Website and using any service provided by this Website, including but not  limited to viewing any of its content or purchasing any ticket or merchandise,  you expressly agree to be bound by this Agreement, and all applicable laws and  regulations governing the use of this Website. <strong>We suggest that you  become familiar with the below especially regarding ticket purchases and  refunds.</strong></p>
    <p><strong>1.  Introduction</strong></p>
    <p>This Website is the  online service provided by Wakpot s.a.r.l, a Lebanese Company (sometimes  referred to herein as the &quot;Company&quot;, &quot;we&quot; or  &quot;our&quot;) with our principal place of business in Beirut, Lebanon, and  on the World Wide Web of the Internet. This Website consists of ticketing  services, which may include facilitating the purchase or sale of tickets to  seminars and workshops, providing access to other ticket resources, and related  content provided by the Company and by third parties.</p>
    <p>This Website is subject to the terms  and restrictions contained herein and is for private personal use by consumers  only. Any other use or attempt to use this Website, or any of the services  provided through this Website for commercial purposes (including the purchase  of tickets for the purpose of resale), directly or indirectly, by you or by a  third party is strictly prohibited.</p>
    <p><strong>2.  Changes in Terms and Conditions</strong></p>
    <p>The Company reserves the right to  change or discontinue any aspect or feature of this Website at any time. This  includes but is not limited to, the right to change or discontinue any service  provided by the Company, content displayed on this Website, hours of availability,  and equipment needed for access or to use this Website, at any time. We also  reserve the right to change or modify the terms and conditions of this  Agreement applicable to your use of this Website, or any service provided  through this Website. We can impose new conditions, including, but not limited  to, adding fees and charges for use at any time. Changes, modifications,  additions or deletions to this Agreement will be effective immediately upon the  posting of a corresponding revised Agreement on this Website. Accordingly,  please review this Agreement periodically to familiarize yourself with the most  current version. Unless expressly stated otherwise, any new features that  augment or enhance the current services provided though this Website also will be  subject to the provisions of this Agreement.</p>
    <p><strong>3.  Permitted Use of This Website</strong></p>
    <p>This Website is the private property  of  Wakpot s.a.r.l. and your access to  this Website is only with our permission. Any unauthorized access or use will  be deemed, among other things, a trespass, and we reserve the right to pursue  our legal rights for any unauthorized access or use of this Website, including  seeking civil remedies and equitable relief to the fullest extent possible, as  well as referral of matters to appropriate law enforcement agencies.</p>
    <p>If you are a consumer seeking  information about an event, activity, conference, seminar or workshop, or if  you are seeking to purchase tickets to any event or facility through this  Website, then you are authorized to enter and use this Website, subject to the  other terms and conditions of this Agreement.</p>
    <p><strong>4.  Prohibited Use of this Website</strong></p>
    <p>You are prohibited from doing any act  that has the effect of undermining the integrity of our system, this Website,  our services and the method by which we provide our services to users.<br />
As a material term of this Agreement,  you expressly agree that you shall <strong>NOT</strong> do any of the following:</p>
    <p>a. Deploy or facilitate the use or  deployment of any robot, spider, scraper or any other automated means, method or  device to view, select or copy any content from this Website;</p>
    <p>b. Deploy or facilitate the use or  deployment of any script, routine, program or any other automated means, method  or device with respect to this Website for any other purpose, including but not  limited to purchasing tickets;</p>
    <p>c. Deploy or facilitate the use or  deployment of any program, system, means, method or device, for any purpose  that places an unreasonable, unnecessary or excessive demand or load on this  Website, its hardware and connections, or prohibits, denies or delays access to  this Website by others;</p>
    <p>d. Purchase tickets to any event  offered through this Website for the purposes of reselling those tickets. If we  determine that you are purchasing an irregularly large number of tickets to an  event or multiple events, we will presume that you are purchasing such tickets  for resale purposes and at our sole election, we will cancel your  transaction(s) and restrict your access to this Website;</p>
    <p>e. Download or copy any content  displayed on this Website for purposes other than preserving information for  your personal use;</p>
    <p>f. Establish any deep link or other  connection to any specific page or pages of this Website other than the home  page, without Company's prior written permission;</p>
    <p>g. Deploy or facilitate the use or  deployment of any automatic or manual device, process or means to circumvent,  avoid or defeat any of our security measures or systems. You expressly agree  that the typing will only be done manually by you on the keyboard of the computer  you are using to access this Website;</p>
    <p>h. Access, reload or refresh this  Website's transactional event or ticketing pages, or make any other request to  this Website's transactional servers, more than once during any two second  interval; or</p>
    <p>i. Request more than 500 pages of this  Website in any twenty-four hour period.</p>
    <p>You expressly agree that you will use  this Website only for lawful purposes. You will not post or transmit through  this Website any material which: (i) violates or infringes in any way upon the  rights of others; (ii) is unlawful, threatening, abusive, defamatory, invasive  of privacy or publicity rights, vulgar, obscene, profane or otherwise  objectionable; (iii) encourages conduct that would constitute a criminal  offense, give rise to civil liability or otherwise violate any law; (iv)  creates or attempts to create any liability of the Company, (v) contains  advertising or any solicitation with respect to products or services, unless we  have approved such material in writing, in advance of its transmission; (vi)  introduces any program, executable file or routine (such as a worm, Trojan  horse, cancelbot, time bomb or virus) into our system for any purpose,  irrespective of whether any such program or routine results in detrimental harm  to our system or our data; or (vii) threatens the continuous services of our  ISP's, suppliers and vendors.</p>
    <p>Any conduct by you that in our sole  discretion restricts, inhibits, or interferes with any other consumer from  using or enjoying this Website is expressly prohibited.</p>
    <p> <strong>5. Currency</strong></p>
    <p>All ticket prices for events that occur in the Middle East and GCC  countries are stated in U.S. Dollars.</p>
    <p><strong>6. Order Confirmation</strong></p>
    <p>If you do not receive a confirmation email) after submitting payment  information, or if you experience an error message or service interruption  after submitting payment information, it is your responsibility to confirm with  the Company whether or not your order has been placed. Only you may be aware of  any problems that may occur during the purchase process. The Company will not  be responsible for losses (monetary or otherwise) if you assume that an order  was not placed because you failed to receive confirmation.</p>
    <p><strong>7. Convenience Charges and Order Processing Fees</strong></p>
    <p>Tickets purchased on nuqat.me are typically subject to a per ticket  convenience charge and a non-refundable per order processing fee valued at 3%  of the purchase amount. The 3% is inclusive within the total price and will not  be refunded in case the consumer asked for a refund.</p>
    <p><strong>8. Number of Tickets Per Customer or &quot;Ticket Limits&quot;</strong></p>
    <p>When purchasing tickets on nuqat.me, you are limited to one ticket per  transaction. This policy is in effect to discourage unfair ticket buying  practices.</p>
    <p><strong>9. Cancelled and Rescheduled Events</strong></p>
    <p>Occasionally, events, conferences, seminars and workshops are canceled  or rescheduled. Should this occur, we will attempt to contact you to inform you  of refund or exchange procedures for that specific activity. For exact  instructions on any canceled or rescheduled concert, please check the information  online or contact us.</p>
    <p>If your event was canceled, and you  already purchased your ticket, in most cases you won't need to do a thing.  We'll inform you of the cancellation and refund the amount you paid for your  tickets. If you bought your tickets on location, please return them at the same  location.</p>
    <p>If your event was rescheduled, we'll  contact you with the new date and time ASAP. In case you can't make it, you&rsquo;ll  be entitled for a refund. </p>
    <p><strong>10. Refunds and Exchanges</strong></p>
    <p>Before purchasing tickets, carefully review your event selection and  details.  Our policies generally prohibit  from issuing exchanges or refunds after a ticket has been purchased or for  lost, stolen, damaged or destroyed tickets. However, most tickets bought online  are fully refundable for 3 calendar days (72 hours) after you purchase them.  Tickets purchased at the event location must be returned or exchanged at the  same location; the event registration desk cannot exchange tickets bought  online. Exceptions to 3-day refund policies include  extreme cases whereas the Company will  evaluate on a case by case basis.</p>
    <p>You agree that you will not attempt to  evade, avoid, or circumvent any refund prohibitions in any manner with regard  to tickets you purchased. Without limiting the generality of the foregoing, you  will not contact seek a &quot;chargeback&quot; from the company whose credit  card you used to purchase tickets from the Site. Should you do so, your tickets  may be cancelled, and the Company may, in its sole discretion, refuse to honor  pending and future ticket purchases made from all credit card accounts or  online accounts on which such chargebacks have been made, and may prohibit all  persons in whose name the credit card accounts exist and any person who  accesses any associated online account or credit card or who otherwise breaches  this provision from using the Site.</p>
    <p>If a refund is issued, it will be  issued using the same method of payment that was used to purchase the tickets.  If a credit card was used to make the refunded purchase, then only that actual  credit card will receive the credit for the refund. The Company will not be  liable for travel or any other expenses that you or anyone else incurs in  connection with a cancelled or postponed event.</p>
    <p><strong>11. Billing  Information Verification</strong></p>
    <p>Orders are processed only after a  billing address, and other billing information, has been verified.  Occasionally, we receive incorrect billing or credit card account information  for a ticket order that can delay processing and delivery. In these cases, the  Company customer service will attempt to contact you, using the information  provided at the time of purchase. If the Company is unable to reach you after  its initial attempt, the Company may cancel your order and may sell your  tickets to another customer without further notice.</p>
    <p>Orders are processed only after a  billing address, and other billing information, has been verified.  Occasionally, we receive incorrect billing or credit card account information  for a ticket order that can delay processing and delivery. In these cases, the  Company customer service will attempt to contact you, using the information  provided at the time of purchase. If the Company is unable to reach you after  its initial attempt, the Company may cancel your order and may sell your  tickets to another customer without further notice.</p>
    <p><strong>12. Delivery</strong></p>
    <p>Once a purchase transaction is made on nuqat.me, you should receive a  confirmation email which is considered as an e-ticket. You&rsquo;ll need to print it  out and bring it with you to the event in order to receive your event pass.</p>
    <p><strong>13. Pricing and Other Errors</strong></p>
    <p>If the amount you pay for a ticket is incorrect regardless of whether  because of an error in a price posted on this website or otherwise communicated  to you, or you are able to order a ticket before its scheduled on-sale or  presale date or you are able to order a ticket that was not supposed to have  been released for sale, then the Company will have the right to cancel that  ticket (or the order for that ticket) and refund to you the amount that you  paid. This will apply regardless of whether because of human error or a  transactional malfunction of this website or other Company operated system.</p>
    <p>Prices include VAT for Lebanese  citizens. </p>
    <p><strong>14. Multiple Browser Windows</strong></p>
    <p>When ordering tickets online with nuqat.me, please ensure you are  looking for tickets and placing an order using only one browser window. Looking  up tickets using multiple browser windows could result in losing your tickets  or timer expiration.</p>
    <p><strong>15. Limitation of Liability</strong></p>
    <p>You voluntarily assume all risks and danger incidental to the event for  which the ticket is issued, whether occurring before, during or after the  event, and you waive any claims for personal injury or death against the  Company, management, facility, artist, participants, and all of their  respective parents, affiliated entities, agents, officers, directors, owners  and employees on behalf of yourself and any accompanying minor. You bear all  risks of inclement weather. Event date and time are subject to change.</p>
    <p><strong>16. License; Ejection and Cancellation; No Redemption Value</strong></p>
    <p>The Company reserve the right, without refund of any amount paid, to  refuse admission to, or eject, any person whose conduct management deems  disorderly, who uses vulgar or abusive language or who fails to comply with the  event rules. Breach of terms or rules will terminate your license to attend the  event without refund. A ticket is a revocable license and admission may be  refused upon refunding the ticket's face amount. A ticket is not redeemable for  cash.</p>
    <p><strong>17. Recording, Transmission and Exhibition</strong></p>
    <p>You agree not to record or transmit, or  aid in recording or transmitting, any description, account, picture, or  reproduction of the event. You agree that the event for which you purchase  tickets is a public event, that your appearance and actions inside and outside  the venue where the event occurs are public in nature, and that you have no  expectation of privacy with regard to your actions or conduct at the event. You  grant permission to the Company  to  utilize your name, image, likeness, acts, poses, plays, appearance, movements,  and statements in any live or recorded audio, video, or photographic display or  other transmission, exhibition, publication or reproduction made of, or at, the  event (regardless of whether before, during or after play or performance) for  any purpose, in any manner, in any medium or context now known or hereafter  developed, without further authorization from, or compensation to, you or  anyone acting on your behalf.</p>
    <p><strong>18. You Are Subject to Search</strong></p>
    <p>You and your belongings may be searched on entry to the event. You  consent to such searches and waive any related claims that may arise. If you  elect not to consent to such searches, you may be denied entry to the event  without refund or other compensation. Under certain facility rules, certain items  may not be brought into the premises, including without limitation, alcohol,  drugs, controlled substances, cameras, recording devices, laser pointers,  strobe lights, irritants (e.g., artificial noisemakers), bundles and  containers.</p>
    <p><strong>19. Unlawful Re-Sale of Tickets; Commercial Purposes</strong></p>
    <p>Unlawful resale (or attempted resale), counterfeit or copy of tickets is  grounds for seizure and cancellation without compensation. In addition, the  Company reserves the right to restrict or deny ticket purchasing privileges to  anyone that the Company determines to be, or has been, in violation of this  policy. Because the Company does not guarantee the authenticity of tickets  purchased from any non-authorized third party reseller (such as brokers or  individuals), the Company recommends that you purchase tickets directly through  nuqat.me, authorized partners or from the venue box office to ensure ticket  authenticity. Tickets may not be used for advertising, promotions, contests or  sweepstakes, unless formal written authorization is given by the Company,  provided that even if such consent is obtained, any use of the Company&rsquo;s  trademarks and other intellectual property is subject to the Company's consent.</p>
    <p><strong>20.  Links to Other Websites</strong></p>
    <p>We may, from time to time, display  icons, graphic or textual links to other websites, or display selected pages of  other websites not affiliated with nuqat.me through framing or other means. Any  content, product or service provided by other websites is subject to the  control of such third parties and the Company. Your access to and use of any  other website, and any transaction in which you engage on any other website, is  subject to the applicable user agreements and privacy policies of that website.  The Company reserves the exclusive right and sole discretion to add, decline or  remove, without notice, any icon or link to another website.</p>
    <p><strong>21.  Electronic Communications</strong></p>
    <p>When you purchase tickets or  merchandise from us, or when you become a registered user with us to facilitate  future transactions, you are communicating with us electronically and by doing  so, you consent to receive electronic communications from us regarding a  purchase you are making or an event to which you have purchased tickets.  Additionally, by consenting to accept electronic communications from us, you  also agree that all agreements, disclosures and notices, including any updates  to this Agreement, may be provided to you electronically and that an electronic  communication from us satisfies any legal requirement that a communication be  in writing.</p>
    <p>In addition, when you purchase tickets  or merchandise from us, or when you become a registered user with us, you agree  that you have established a business or personal relationship with the Company  and you consent to receive email notices or advertisements from us in the  future about events, products or services that may be of interest to you. If  you are not interested in receiving email notices or advertisements from us,  you should unsubscribe now.</p>
    <p><strong>22.  Downloading Of Intellectual Property</strong></p>
    <p>This Website contains proprietary  material and information, including without limitation, the &quot;look and  feel&quot; of this Website. All design, text, software, images, trade names,  logos and other information presented on this Website is protected under copyright  laws and is owned by the Company or is used under license from the owner of the  respective intellectual property rights. In addition, the entire contents of  this Website are copyrighted as a collective work/compilation. The Company owns  copyrights in the selection, coordination, arrangement, and enhancement of such  content, as well as in the content original to it. You may not modify, publish,  transmit, participate in the transfer or sale, create derivative works, or in  any way exploit, any of the content, in whole or in part. If you are a  consumer, you may download copyrighted material for your personal use only.  Except as otherwise expressly permitted under copyright law, no copying,  redistribution, retransmission, publication or commercial exploitation of downloaded  material will be permitted without the prior written permission of the Company  (and the copyright owner if other than the Company). If you are given  permission to copy, redistribute or publish copyrighted material, you may not  delete author attribution, trademark legends or copyright notices. You  expressly acknowledge that you do not acquire any ownership rights by  downloading copyrighted material.</p>
    <p><strong>23.  Disclaimers, Releases</strong></p>
    <p>YOU AGREE THAT  USE OF THIS WEBSITE IS AT YOUR OWN RISK. YOU WILL BE RESPONSIBLE FOR PROTECTING  THE CONFIDENTIALITY OF YOUR PASSWORD, IF ANY. NEITHER THE COMPANY, ITS PARENT  COMPANY, NOR ANY OF THEIR RESPECTIVE EMPLOYEES, SHAREHOLDERS, AGENTS, THIRD  PARTY CONTENT PROVIDERS OR LICENSORS, WARRANT THAT YOUR USE OF THIS WEBSITE  WILL BE UNINTERRUPTED OR ERROR FREE; NOR DO THEY MAKE ANY WARRANTY AS TO THE  RESULTS THAT MAY BE OBTAINED FROM USE OF THIS WEBSITE, OR AS TO THE ACCURACY,  RELIABILITY OR CONTENT OF ANY INFORMATION, SERVICE, OR MERCHANDISE PROVIDED  THROUGH THIS WEBSITE. THIS WEBSITE IS PROVIDED ON AN &quot;AS IS&quot; BASIS  WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT  LIMITED TO, WARRANTIES OF TITLE OR IMPLIED WARRANTIES OF MERCHANTABILITY OR  FITNESS FOR A PARTICULAR PURPOSE, OTHER THAN THOSE WARRANTIES WHICH ARE IMPLIED  BY AND INCAPABLE OF EXCLUSION, RESTRICTION OR MODIFICATION UNDER THE LAWS  APPLICABLE TO THIS AGREEMENT. THE DISCLAIMERS CONTAINED IN THIS AGREEMENT APPLY  TO ANY DAMAGES OR INJURY CAUSED BY ANY FAILURE OF PERFORMANCE, ERROR, OMISSION,  INTERRUPTION, DELETION, DEFECT, DELAY IN OPERATION OR TRANSMISSION, COMPUTER  VIRUS, COMMUNICATION LINE FAILURE, THEFT OR DESTRUCTION OR UNAUTHORIZED ACCESS  TO, ALTERATION OF, OR USE OF RECORD, WHETHER FOR BREACH OF CONTRACT, TORTUOUS  BEHAVIOR, NEGLIGENCE, OR UNDER ANY OTHER CAUSE OF ACTION. YOU SPECIFICALLY  ACKNOWLEDGE THAT NEITHER THE COMPANY NOR ITS PARENT COMPANY IS LIABLE FOR THE  DEFAMATORY, OFFENSIVE OR ILLEGAL CONDUCT OF OTHER USERS OR THIRD PARTIES AND  YOU ASSUME THE RISK OF INJURY FROM ANY OF THE FOREGOING.</p>
    <p>IN NO EVENT WILL THE COMPANY, ITS  PARENT COMPANY, OR ANY PERSON OR ENTITY INVOLVED IN CREATING, PRODUCING OR  MAINTAINING THIS WEBSITE BE LIABLE FOR ANY DAMAGES, INCLUDING, WITHOUT  LIMITATION, DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES  ARISING OUT OF THE USE OF OR INABILITY TO USE THIS WEBSITE. BECAUSE SOME  JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR  CONSEQUENTIAL DAMAGES, THE ABOVE EXCLUSIONS OF INCIDENTAL AND CONSEQUENTIAL  DAMAGES MAY NOT APPLY TO YOU, BUT WILL APPLY, IN ANY EVENT, TO THE MAXIMUM  EXTENT POSSIBLE.</p>
    <p>IN ADDITION TO THE TERMS SET FORTH  ABOVE, NEITHER THE COMPANY NOR ITS PARENT COMPANY, INFORMATION PROVIDERS, OR  CONTENT PROVIDERS WILL BE LIABLE REGARDLESS OF THE CAUSE OR DURATION, FOR ANY  ERRORS, INACCURACIES, OMISSIONS, OR OTHER DEFECTS IN, OR UNTIMELINESS OF, THE  INFORMATION CONTAINED WITHIN THIS WEBSITE, OR FOR ANY DELAY OR INTERRUPTION IN  THE TRANSMISSION THEREOF TO ANY USER, OR FOR ANY CLAIMS OR LOSSES ARISING FROM  USING THIS WEBSITE. NONE OF THE FOREGOING PARTIES WILL BE LIABLE FOR ANY  THIRD-PARTY CLAIMS OR LOSSES OF ANY NATURE, INCLUDING, BUT NOT LIMITED TO, LOST  PROFITS, PUNITIVE OR CONSEQUENTIAL DAMAGES.</p>
    <p>YOU EXPRESSLY ACKNOWLEDGE THAT YOU MAY  HAVE OR MAY IN THE FUTURE HAVE CLAIMS AGAINST THE COMPANY WHICH YOU DO NOT NOW  KNOW OR SUSPECT TO EXIST IN YOUR FAVOR WHEN YOU AGREED TO THE TERMS AND  CONDITIONS OF THIS AGREEMENT, AND WHICH IF KNOWN, MIGHT MATERIALLY AFFECT YOUR  CONSENT TO THE TERMS AND CONDITIONS OF THIS AGREEMENT. YOU EXPRESSLY WAIVE ALL  RIGHTS YOU MAY HAVE.</p>
    <p><strong>24.  Trademarks</strong></p>
    <p>Nothing contained in this website  should be construed as granting by implication, estoppel, or otherwise, a  license or right to use any trademarks displayed on this Website without the  prior written permission of Tickets.com, Inc., or their respective owners.</p>
    <p><strong>25.  Breach</strong></p>
    <p>Without limiting any other remedies  that we may have available at law or in equity, upon our confirmation that you  have breached any provision of this Agreement or the agreements referenced in  this Agreement, we may, without notice, cancel any pending transactions you may  have with us and restrict or deny your access to our Website and services,  including any services we provide through channels other than the Internet. You  acknowledge and agree that monetary damages may not be a sufficient remedy to  the Company for a breach of this Agreement and you consent to injunctive or  other equitable relief for any alleged breach.</p>
    <p><strong>26.  Binding Arbitration</strong></p>
    <p>Any dispute relating to or arising from  your purchase of any tickets or other merchandise through this Website; or  arising under this Agreement, in which monetary damages are being sought, will  be resolved by binding arbitration conducted in accordance with the Governing  Laws of Lebanon. To the extent practicable, hearings will be conducted via  telephone or other electronic means intended to facilitate a forum in which a  hearing may be had. Any in-person arbitration proceeding will take place in  Beirut, Lebanon. Upon conclusion of the arbitration, any court having  jurisdiction over the matter may enter judgment on any award issued in the  arbitration.</p>
    <p><strong>27.  Legal Proceedings</strong></p>
    <p>Any legal proceeding, which is  commenced for the purposes of seeking injunctive or other equitable relief,  will be adjudicated by a court of competent jurisdiction sitting in Lebanon and  you and the Company expressly consent to the personal jurisdiction of Lebanon.</p>
    <p><strong>28.  Indemnification</strong></p>
    <p>You agree to save defend, indemnify and hold the Company, its parent  company, and their respective directors, officers, shareholders, employees,  agents, and assigns harmless from and against all claims and expenses,  including attorneys' fees, arising out of your use of this Website, including  but not limited to any use of this Website that is not authorized by this  Agreement</p>
    <p><strong>29.  Notices</strong></p>
    <p>All notices regarding any matter  pertaining to this Agreement, or the policies referenced herein, including any  notice of claim, summons or subpoena will be given by first class mail or  courier, postage or air bill prepaid, and sent to: Wakpot s.a.r.l., Center  Mirna Tawk, Chalet Suisse St. Al Fanar, Mount Lebanon, Lebanon. Notice will be  deemed effective 3 days after deposit with the courier. In addition, the  Company may provide notice to you by either email or Certified Mail, postage  prepaid and return receipt requested, sent to the physical or email address you  provided to us during any transaction conducted with us. Notice will be deemed  effective 24 hours after sending of an email (unless returned due to an invalid  email address) or 3 days after mailing.</p>
    <p><strong>30.  General</strong></p>
    <p>This Agreement is to be construed in  accordance with the laws of the Lebanon, without regard to its conflict of laws  provisions. This Agreement, as updated from time to time, constitutes the  entire agreement between us, with respect to the terms and conditions of use of  this Website and supersedes all previous written or oral agreements between us.  If any provision of this Agreement is held to be invalid or unenforceable, such  provision will be struck and the remaining provisions will be enforced. The  section headings in this Agreement are for reference purposes only and in no  way limit or describe the scope of a particular section. Our failure to enforce  any breach of this Agreement by you or others does not mean that we have waived  our right to enforce the terms of this Agreement in the future for a similar  breach. </p>
    <p>&nbsp;</p></td>
    </tr>
  <tr>
    <td colspan="5">&nbsp;</td>
  </tr>

</table>
